### PR TITLE
Disallow extra else in regular expressions

### PR DESCRIPTION
**Pull request by zinyando**
I'm not really sure if I'm doing the right thing here so please point me in the right direction if I'm lost. Part of issue #159. I'm testing regexs where there is no condition to check after an alternation `|` eg

```
let reg = /|Hello|World|/;
```

The result looks like this

Screenshot 2020-03-12 at 13 21 08

### CODE REVIEW

**Comment by zinyando** [comment]
@sebmck seems like the rule has already caught a lint violation in the Rome code, is it safe to remove the extra `|`?

Screenshot 2020-03-12 at 13 25 25

**Comment by sebmck** [comment]
It's acceptable to have an empty alternate. For example, `/(Sebastian)( McKenzie|)/` would allow matching "Sebastian" and "Sebastian McKenzie".

**Comment by sebmck** [comment]
@zinyando Hey! Is there anything I can do to help with this PR? The only change should be changing the current condition to only error on the second occurence.

**Comment by zinyando** [comment]
@sebmck hey, I don't understand what you mean by `The only change should be changing the current condition to only error on the second occurrence.`. Can you show me an example regex that I'd want to throw an error on?

**Comment by sebmck** [comment]
We would want to allow:

```
/Sebastian|Lennex|/
```

As that would match either "Sebastian", "Lennex", or nothing.

But we would want to disallow:

```
/Sebastian|Lennex||/
```

Note the two trailing `|`.

That would match "Sebastian", "Lennex", nothing, or nothing. Making the presence of one empty group unnecessary.

To do this, you'd want to add a check to `RegExpAlternation` that would flatten the `left` and `right` sides like this:

```
if (node.type === 'RegExpAlternation') {
  const subs: Array<RegExpSubExpression> = [];

  let alternation: AnyRegExpExpression = node;
  while (alternation !== undefined) {
    if (alternation.type === 'RegExpSubExpression') {
      subs.push(alternation);
    } else {
      subs.push(alternation.right);
      alternation = alternation.left;
    }
  }
}
```

Then loop through it, and ignore the first `sub.body.length === 0` that you see, but error on all subsequent occurrences.

**Comment by sebmck** [comment]
Hey @zinyando! I'm going to close this out. Feel free to reopen if you're able to pick this up again. Thank you!

**Pull request closed without merging**
