### PR TITLE
add rule jsxA11y alt text and tests

### PR DESCRIPTION
**Pull request by VictorHom**
[rule](https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/docs/rules/alt-text.md)

from #341

### CODE REVIEW

**Comment by sebmck** [comment]
Nice! I added some JSX helpers in #445. Could you update this PR to use them instead for the attribute inspection? Should make it a lot cleaner.

**Comment by VictorHom** [comment]
sweet. thanks for the reference. this is v. helpful. Still getting used to navigating around the codebase

**Comment by VictorHom** [comment]
for the cases of `;` `isEmptyAttributeValue` won't be applicable.

What are your thoughts on this? 
- add case to isEmptyAttributeValue (I don't like it. it seems like it doesn't quite fit the definition of isEmptyAttributeValue)
- or add as a conditional check in the rule to consider TemplateLiterals
- or not consider this case

**Comment by sebmck** [comment]
I don't think it's worth considering. That code seems really unlikely to ever occur.

**Comment by sebmck** [comment]
Thank you!

**Pull request merged**
