### PR TITLE
Disallow unmatched opening square bracket in regular expressions

### PR DESCRIPTION
**Pull request by baryla**
The rule does pick out the opening square bracket but for some reason, the error underline is not right? 

Screenshot 2020-03-15 at 15 46 30

Btw. sorry about the long lint name 😂I'm open to better suggestions 😂

### CODE REVIEW

**Comment by baryla** [comment]
As pointed out by @KevinKelbie in the discord channel, there's some more work that needs to be done.

**Comment by sebmck** [comment]
@baryla 

> As pointed out by @KevinKelbie in the discord channel, there's some more work that needs to be done.

I think I missed that conversation. What's remaining?

**Comment by KevinKelbie** [comment]
@sebmck here is a link to the discussion we had: https://discord.com/channels/678763474494423051/678763474930761739/688778390408527923

**Comment by sebmck** [comment]
Closing this out due to inactivity. Feel free to open a new PR if you'd like to pick this up again! Thank you!

**Pull request closed without merging**
