### PR TITLE
Add jsxNoLiterals rule

### PR DESCRIPTION
**Pull request by yeonjuan**
[rule link]( https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-no-literals.md) ,ref #341

### CODE REVIEW

**Comment by bitpshr** [comment]
This rule looks good so far, but I'm a little hesitant about the rationale behind it. It feels slightly restrictive to disallow common JSX syntax like `<div>foo</div>` and to instead require JSX syntax like `<div>{'foo'}</div>`. I understand this rule being useful in an application that uses an i18n translation engine, so any string literal could be untranslated and a potential error, but that feels application-specific.

Are there other reasons for including this rule besides general style preference?

**Comment by ematipico** [comment]
I too think that this rule is too restrictive and I don't see any reason why we should adopt it. 

Lot of times there's need to have a simple string. And we save also characters.

**Comment by yeonjuan** [comment]
@bitpshr , @ematipico 
Yes, right. It's quite useful for i18n translation engine. If it seems too restrictive in normal cases, I don't mind close this PR.

**Comment by bitpshr** [comment]
Sorry about that @yeonjuan! I’ll try to get the Google document properly updated to avoid future confusion. This pull request looks great otherwise for what it’s worth, so thanks a ton for the effort here.

**Comment by yeonjuan** [comment]
Thanks for the reply. I 'll close it

**Pull request closed without merging**
