### PR TITLE
add rule no danger props and tests

### PR DESCRIPTION
**Pull request by VictorHom**
The rule is from [here](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-danger.md)

It's based on the list in #341 

Also the credit pretty much goes to @bitpshr in his pr #421

### CODE REVIEW

**Comment by VictorHom** [comment]
@sebmck not sure what the issue is with ci error. can you help me when you have a chance?

**Comment by bitpshr** [comment]
I think this rule should be considered carefully before it's landed. It's not a recommended rule, it's not used by `create-react-app`, and the less-restrictive `react/no-danger-with-children` rule is already implemented. If this rule does end up landing, `react/no-danger-with-children` should in turn be removed to prevent duplicate warnings when `children` is set.

**Comment by VictorHom** [comment]
@bitpshr good point. not familiar with what's used in `react-create-app`, but I agree with that the duplicated messaging wouldn't be good

**Comment by sebmck** [comment]
This looks reasonable. We are going with the strategy of "over the top" lint rules with suppressions preferred. This is one of the things that is wrong 99% of the time. What do you think about the rule overlap?

**Comment by bitpshr** [comment]
Thinking about this more, rule overlap isn't a bad thing and will happen in other cases, too. For example, duplicate object keys will be checked in addition to duplicate JSX props, even though they technically overlap in the case of `createElement`. Throwing different (or tangentially-related) errors for the same lines won't hurt anything.

**Comment by sebmck** [comment]
Sounds good to me. We can fine tune our strategy in the future if it turns out to be excessive.

**Comment by sebmck** [comment]
Thanks all!

**Pull request merged**
