### PR TITLE
Website update

### PR DESCRIPTION
**Pull request by EduardoLopes**
- Add a sidebar on the right with the table of contents
- When on mobile, the right sidebar appears together with the left sidebar and each one takes 50% of the screen. so it is a fullscreen menu now!
- Add a new style for the color scheme switch (now, it is on the right sidebar)
- Style home page actions

Since the start idea was to make a single page with all the documentation, i made the table of content h2 titles disappear when it's h1 title wasn't active, because it could get quite big. That's not necessary anymore, so this feature was removed. 

For some reason, the favicon didn't have a transparent background. Now it's fixed!

### CODE REVIEW

**Comment by sebmck** [comment]
> For some reason, the favicon didn't have a transparent background. Now it's fixed!

I deliberately gave it a background (It should have been noted in one of my previous PRs). In a dark mode browser the favicon looks really bad because the black is invisible.

**Comment by EduardoLopes** [comment]
Didn't notice, sorry. i'll revert the commit

**Comment by sebmck** [comment]
All good! I think the one I replaced it with still looks pretty bad. Is there some variant you think would look good on a light/dark background?

**Comment by sebmck** [comment]
(Your changes look great though! Feel free to merge whenever you like)

**Comment by EduardoLopes** [comment]
@sebmck Next update, i'll try all yellow and see how it looks!

**Pull request merged**
