### PR TITLE
WIP: New website

### PR DESCRIPTION
**Pull request by EduardoLopes**
[Current look](https://deploy-preview-507--romejs-indep.netlify.app/)

Still missing:

- [x] Dark Mode
- [x] Menu for others pages (I think it's good on the sidebar)
- [x] Support for screen-readers
- [ ] Finish (review) documentation

### CODE REVIEW

**Comment by sebmck** [comment]
Woah, I like it! Haven't reviewed anything yet but I really like the design screenshots.

**Comment by matvp91** [comment]
@sebmck imo the only thing left in order to replace the Docusaurus build is a proper footer. Could you double check if I'm missing something? If not, I should get this done during the weekend.

**Comment by matvp91** [comment]
There's a separate section in https://github.com/romejs/rome/pull/509 for "Linting", although it's not a seperate page.

I agree with your first comment, the shorter the docs, the easier it gets for people to read through them.

**Comment by matvp91** [comment]
We're getting to a point where the new documentation is good enough to be released. Although, I'd like to raise several questions that are worth discussing:

- Will there ever be a need for a top navigation bar? If not, I'd like to figure out something different. The fact that we have a fixed navbar on top (that is especially visible on mobile), makes the titles show below the fixed header when we navigate to a different anchor. (1)
-  Clicking nav items will only be in "active" state after the scroll animation, user actions should have immediate feedback. (1)
- There's a bunch of improvements that can be made on mobile:
  - When using the sidebar to navigate to a different anchor, we should close the sidebar.
  - The sidebar does not fully cover the width of the screen, clicking outside should close the sidebar (preferrably a semi transparant black background to keep focus on the menu).
- Support for screen-readers / wai-aria.
- Anchors do not update when scrolling through the page, this will cause confusion when people start sharing sections. (1)

1) These should be fixed in our own TOC implementation, this requires us to write a bit of JavaScript, let's use Rome to transpile the JS written for the docs.

**Comment by KevinKelbie** [comment]
This is looking really good so far!

The "Testing" and "Type checking" sections are not highlighted on the nav unlike all the other elements:
Screenshot 2020-05-24 at 14 51 54

**Comment by EduardoLopes** [comment]
If there will be others pages, i think we should use the top bar for that. And keep only table of contents in the sidebar. Or make a section in the side bar, for links that will lead to another page, so the user know what each type of link makes once you click! The top bar seems like a better solution.

Generate the TOC on a build step in Eleventy would be great.

**Comment by EduardoLopes** [comment]
@KevinKelbie it's because you can't go all the way down so the heading get close to the top and highlight

**Comment by EduardoLopes** [comment]
@matvp91
> When using the sidebar to navigate to a different anchor, we should close the sidebar.
Didn't really got this line. Clicking a toc link should close the sidebar?

**Comment by matvp91** [comment]
@EduardoLopes correct, I assume when someone clicks on a TOC item, they'll want to see the content afterwards.

Nice work!

**Comment by EduardoLopes** [comment]
@matvp91 got it. Done!

**Comment by sebmck** [comment]
Just added a `yarn.lock` file. I don't have a package manager preference but the existing netlify deploy config uses the `yarn build` command which is why the deploy preview is failing.

**Comment by sebmck** [comment]
Once the deploy preview is working it'll make this a lot easier. What do you all prefer in terms of merging? We could either freeze `romejs.dev`, and move this to `preview.romejs.dev` and merge this PR. Or we can use this branch/PR as the source of truth and merge it when we're ready for a release.

**Comment by sebmck** [comment]
Deploy preview is working (just click Details next to the `deploy/netlify` status check). For some reason the CSS isn't working though and 404s.

**Comment by sebmck** [comment]
[It works!](https://deploy-preview-507--romejs-indep.netlify.app/)

**Comment by EduardoLopes** [comment]
I think we should use this branch until it's ready. Let's finish this week!

**Comment by EduardoLopes** [comment]
(looks like the tasks for my netlify deploy i was debugging shows here, didn't know that. sorry. but it's fixed :) )

**Comment by EduardoLopes** [comment]
- Tocbox was removed
- Now the table of contents is generated on build step
* Don't use any library to highlight the table of contents! I've write the code for that, and fixed the issues mentioned above: 
  - Immediate feedback when clicking a link
  - On mobile, the top bar doesn't cover headings when clicking in a table of content's link.

Even though the highlight of the links in the table of contents is a easy task, i've spent most of my time fighting scroll bugs on mobile, then (half a day latter haha) i realize that it was caused by browser sync ghost scroll feature and not bugs in my code. The first version of the code i wrote, was optimized and probably functional, but i rewrote the code in another way, trying to fix the bugs caused by browser sync, and it's not optimized anymore. But it's working, and will not be a problem since there's no much links in the toc. I'll optimize it latter, if necessary!

The others diferences are visual tweaks and fixes.

**Comment by EduardoLopes** [comment]
I think we should choose between npm or yarn and update netlify deploy settings. So we don't keep two files for package locking and can run scripts inside scripts. The way is it right now, it's easy to have a build that work locally, but not on netlify.

**Comment by sebmck** [comment]
This PR should use yarn until it's merged and then a decision can be made for whatever. I can't change the netlify build command without breaking `master`.

**Comment by EduardoLopes** [comment]
Dark mode is basically finished. I just need to find a place for the toggle button. Right now, it's in the footer. I think i'll place it at the bottom of the side bar.

**Comment by kennetpostigo** [comment]
Should there be a dedicated section to testing? Documenting the built-in test framework api?

**Comment by sebmck** [comment]
Preferrably not. The only thing that should be documented is the linter which is the only part we will actively support and ensure compatibility across semver. Might be worth documenting the basics of the testing API for contributors though.

**Comment by EduardoLopes** [comment]
I did my best to support screen readers. Would be nice if anyone here, with more experience on making web pages accessibly, review the website and point out if i'm missing something. 

The markdown compiler doesn't compile the content to semantic html. Each part with a heading should be separated by sections tags. But this is how github compiles markdown anyways, so i think there's no problems for screen readers?! i'm not sure

This is the document structure right now:

- 1 [document] Rome
  - 1 [nav] Site Navigation
  - 2 [nav] Page Navigation
- 2 [h1] Your next-gen JavaScript toolchain.
  - 1 [h2] Focus on code, let Rome take care of the rest!
- 3 [h1] Introduction
- 4 [h1] Installation
- 5 [h1] Getting started
- 6 [h1] Usage
  - 1 [h2] rome init
  - 2 [h2] rome run
  - 3 [h2] rome lint
  - 4 [h2] rome compile
  - 5 [h2] rome parse
- 7 [h1] Linting
  - 1 [h2] Interpreting the result
  - 2 [h2] Example
- 8 [h1] Contributing
  - 1 [h2] Testing
  - 2 [h2] Type checking
- 9 [h1] Footer
  - 1 [nav] Community
  - 2 [nav] Resources

**Comment by sebmck** [comment]
Thank you so much for the work @EduardoLopes and @matvp91! I'm going to merge this so we can be more incremental with documentation changes and review. I'm going to let the site build and deploy to `https://romejs.dev/` then I'll change the site to just a white page with "Coming soon" since having the current website up is confusing. Later we can then switch it over.

**Pull request merged**
