### PR TITLE
 Switch to hard tabs 

### LINKED ISSUE #425: Hard Tabs
People are allowed to have opinions on how much visual indentation they want in their code. When I first started coding I found 4-space indentation to be really helpful when I would easily get lost in my code. After a few years I preferred 2-spaces. So there is an argument to be made about accessibility.

People have debated endlessly about tabs vs spaces, and ultimately most of people's opinions are just a bit silly. There is only one consequential difference between the two:

Tabs allow individuals in the same codebase to select their indentation widths across every tool (yes including GitHub using either the `.editorconfig` or a user-style with [`tab-size`](https://developer.mozilla.org/en-US/docs/Web/CSS/tab-size)), and spaces do not (at least not across every tool).

As such, I think we should switch to hard tabs for everything in Rome.

I'm gonna make a request that people refrain from flooding this thread with subjective opinions about if 2-space width code is better than 4-space width code. You are welcome to have your personal preference, that is the entire reason for choosing hard tabs.

### PR DESCRIPTION
**Pull request by sebmck**
Closes #425

### CODE REVIEW

**Comment by samccone** [comment]
byebye blame.

**Comment by ljharb** [comment]
Git has a feature now where you can skip over commits like this in the blame.

**Comment by samccone** [comment]
TIL: https://git-scm.com/docs/git-blame#Documentation/git-blame.txt---ignore-revltrevgt
@sebmck perhaps adding a `.git-blame-ignore-revs` file would be helpful.

Thanks for the info @ljharb really cool!

**Comment by sebmck** [comment]
@samccone 

> perhaps adding a .git-blame-ignore-revs file would be helpful.

Want to submit a PR?

**Pull request merged**
